server:
  port: 8080

#切换配置
spring:
  profiles:
    active: dev
#    active: prod

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.move.fast.module.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.move.fast.config.MybatisPlusLogConf
  global-config:
    db-column-underline: true
    id-type: 0

#配置分区
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gateofbabylon?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false

gateOfBabylon:
  log:
    write-grade: debug
    mybatis-plus:
      result-print: true
  proxy:
    is-start: true
    host: 127.0.0.1
    port: 10808
  api:
    notice:
      push-plus-token:
    youdao:
      ocr:
        key:
        secret:
      ocr-trans:
        key:
        secret:
      translate:
        key:
        secret:

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://prod_url:port/gateofbabylon?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false

gateOfBabylon:
  log:
    write-grade: info
    mybatis-plus:
      result-print: false
  proxy:
    is-start: false
    host: 127.0.0.1
    port: 10808
  api:
    notice:
      push-plus-token:
    youdao:
      ocr:
        key:
        secret:
      ocr-trans:
        key:
        secret:
      translate:
        key:
        secret:

---