server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://url/gateofbabylon?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.move.fast.module.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-column-underline: true
    id-type: 0

gateOfBabylon:
  proxy:
    host: 127.0.0.1
    port: 10808
  api:
    notice:
      push-plus-token:
    youdao:
      ocr:
        key:
        secret:
      translate:
        key:
        secret:

