### 手动更新库存并获取链接
GET http://localhost:8080/vpn/stockUp/{num}

### 设置更新
GET http://localhost:8080/vpn/upset/{key}/{value}

### 获取rss订阅
GET http://localhost:8080/vpn/down/{clientType}

### 获取rss订阅
GET http://localhost:8080/vpn/cd/{clientType}/{id}
